---
- name: Provision AAP server (if necessary)
  hosts: satellite
  vars_files:
    - extra_vars.yml
    - sat_repos.yml

  environment:
    SATELLITE_SERVER_URL: "{{ satellite_server_url }}"
    SATELLITE_USERNAME: "{{ satellite_username }}"
    SATELLITE_PASSWORD: "{{ satellite_password }}"

  tasks:
    - name: Setup activationkey # noqa: args[module]
      redhat.satellite.activation_key:
        name: "{{ host_activation_key_9 }}"
        lifecycle_environment: "Library"
        content_view: "Default Organization View"
        state: present
        organization: "{{ satellite_organization }}"

    # Set up host group "hosts"  (test)
    - name: RHEL 9 host group # noqa: args[module]
      redhat.satellite.hostgroup:
        name: "rhel9-server"
        organization: "Default Organization"

    - name: Provision AAP server # noqa: args[module]
      redhat.satellite.host:
        name: "{{ aap_server }}"
        hostgroup: rhel9-server
        provision_method: image
        compute_resource: "libvirt hypervisor"
        image: "rhel-9.3"
        location: "{{ satellite_location }}"
        organization: "{{ satellite_organization }}"
        state: present
      register: host_info
      notify: wait_for_build

    - name: Is host powered on? (would be off if newly provisioned) # noqa: args[module]
      redhat.satellite.host_power:
        name: "{{ aap_server }}"
        state: state
      register: host_state

    - name: Enable build state if new build # noqa: args[module]
      redhat.satellite.host:
        build: true
        name: "{{ aap_server }}"
      when: host_state.power_state is match('off')

    - name: If machine is down, power on  # noqa: args[module]
      redhat.satellite.host_power:
        name: "{{ aap_server }}"
        # yamllint disable rule:truthy
        state: on
        # yamllint enable rule:truthy
      notify: wait_for_build

  handlers:
    - name: Wait until server build is complete
      listen: wait_for_build
      ansible.builtin.command:
        cmd: hammer host status --id "{{ host_info.entity.hosts.0.id }}" --type build
      changed_when: false
      register: result
      until: result.stdout.find("Installed") != -1
      retries: 30
      delay: 15
