---
# code: language=ansible
# Delete NFS server key (locally)
- name: Delete satellite
  hosts: controller
  # connection: local

  tasks:
    - name: Remove nfs server key
      ansible.builtin.known_hosts:
        name: "{{ nfs_server }}"
        state: absent

  #  - name: Delete satellite server
  # FIXME
