---
# code: language=ansible
# Provision cloud instance on libvirt environment
- name: Deploys VM based on cloud image
  hosts: host4.home
  gather_facts: true
  become: true
  vars_files:
    - extra_vars.yml
  vars:
    pool_dir: "{{ kvm_provision_libvirt_pool_dir }}"
    vm: test-rhel8
    vcpus: 2
    ram_mb: 12288
    cleanup: false
    net: default
    ssh_pub_key: "{{ lookup('file', '/home/cgs/.ssh/id_rsa.pub') }}"

  tasks:
    - name: KVM Provision role
      ansible.builtin.include_role:
        name: kvm_provision
      vars:
        kvm_provision_vm_name: "{{ vm }}"
        kvm_provision_vm_vcpus: "{{ vcpus }}"
        kvm_provision_vm_ram_mb: "{{ ram_mb }}"
        kvm_provision_vm_net: "{{ net }}"
        kvm_provision_cleanup_tmp: "{{ cleanup }}"
        kvm_provision_ssh_key: "{{ ssh_pub_key }}"
