---
# code: language=ansible
- name: Setup satellite for provisioning
  # gather_facts: false
  hosts: satellite-16
  become: true
  vars_files:
    - extra_vars.yml
    - sat_repos.yml

  tasks:
    - name: Setup DNS, DHCP  and TFTP
      ansible.builtin.include_role:
        name: redhat.satellite_operations.installer
      vars:
        satellite_installer_scenario: satellite # noqa: var-naming[no-role-prefix]
        satellite_installer_options:
          - "--foreman-proxy-dns true"
          - "--foreman-proxy-dns-managed true"
          - "--foreman-proxy-dns-interface eth0"
          - "--foreman-proxy-dns-zone {{ satellite_domain }}"
          - "--foreman-proxy-dns-reverse 50.168.192.in-addr.arpa"
          - "--foreman-proxy-dhcp true"
          - "--foreman-proxy-dhcp-managed true"
          - "--foreman-proxy-dhcp-interface eth0"
          - "--foreman-proxy-dhcp-range '192.168.50.50 192.168.50.150'"
          - "--foreman-proxy-dhcp-gateway {{ satellite_gateway }}"
          - "--foreman-proxy-dhcp-nameservers 192.168.50.2"
          - "--foreman-proxy-tftp true"
          - "--foreman-proxy-tftp-managed true"
          - "--foreman-proxy-tftp-servername 192.168.50.2"
      # tags:
      #   - never

    # - name: Point DNS to self
    #   ansible.builtin.include_role:
    #     name: linux-system-roles.network
    #   vars:
    #     network_connections:
    #       - name: eth0
    #         type: ethernet
    #         state: up
    #         ip:
    #           gateway4: "192.168.50.1"
    #           address:
    #             - "192.168.50.2/24"
    #           dns:
    #             - "192.168.50.2"
    #           dns_search:
    #             - "devel.net"


    - name: Setup domain
      redhat.satellite.domain:
        name: "{{ satellite_domain }}"
        description: "{{ satellite_domain }}"
        dns_proxy: "{{ satellite_server }}"
        server_url: "{{ satellite_server_url }}"
        username: "{{ satellite_username }}"
        password: "{{ satellite_password }}"

    - name: Setup subnet
      ansible.builtin.include_role:
        name: redhat.satellite.subnets
      vars:
        satellite_subnets: # noqa: var-naming[no-role-prefix]
          - name: "{{ satellite_domain }}"
            network: "192.168.50.0"
            mask: "255.255.255.0"
            gateway: "{{ satellite_gateway }}"
            dns_primary: "192.168.50.2"
            ipam: "DHCP"
            dns_proxy: "satellite.{{ satellite_domain }}"
            tftp_proxy: "satellite.{{ satellite_domain }}"
            dhcp_proxy: "satellite.{{ satellite_domain }}"
            discovery_proxy: "satellite.{{ satellite_domain }}"
            remote_execution_proxies: satellite.{{ satellite_domain }}"
            domains:
              - "{{ satellite_domain }}"
