download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/mdellweg-filters-0.0.3.tar.gz
format_version: 1.0.0
name: filters
namespace: mdellweg
server: https://galaxy.ansible.com/api/
signatures: []
version: 0.0.3
version_url: /api/v3/plugin/ansible/content/published/collections/index/mdellweg/filters/versions/0.0.3/
